version: '3'

services:
  django:
    image: pythondigest/pydigest-classifier:${COMMIT_TAG}
    container_name: pydigest_classifier
    ports:
      - "127.0.0.1:8100:8100"
    command: gunicorn src.api.server:app --bind 0.0.0.0:8100
