version: '3'

services:
  classifier:
    image: pythondigest/pydigest-classifier:${COMMIT_TAG}
    container_name: pydigest_classifier
    ports:
      - "8100:8100"
    command: gunicorn src.api.server:app --bind 0.0.0.0:8100
    networks:
      - py_digest

networks:
  py_digest:
    external: true
